/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#005236",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#dce2f3",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-surface": "#2a313d",
        "surface-container-low": "#f0f3ff",
        "error": "#ba1a1a",
        "tertiary": "#684000",
        "tertiary-container": "#885500",
        "surface-tint": "#4d44e3",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "outline": "#777587",
        "on-background": "#151c27",
        "secondary": "#006c49",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-fixed": "#2a1700",
        "surface-container": "#e7eefe",
        "inverse-on-surface": "#ebf1ff",
        "on-secondary-container": "#00714d",
        "secondary-fixed": "#6ffbbe",
        "background": "#f9f9ff",
        "surface": "#f9f9ff",
        "on-tertiary-container": "#ffd4a4",
        "surface-dim": "#d3daea",
        "secondary-container": "#6cf8bb",
        "on-surface-variant": "#464555",
        "error-container": "#ffdad6",
        "on-surface": "#151c27",
        "surface-container-highest": "#dce2f3",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#3323cc",
        "tertiary-fixed-dim": "#ffb95f",
        "primary": "#3525cd",
        "surface-bright": "#f9f9ff",
        "primary-fixed": "#e2dfff",
        "surface-container-high": "#e2e8f8",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#ffddb8",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#4f46e5"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "md": "16px",
        "lg": "24px",
        "margin-mobile": "16px",
        "max-width": "1440px",
        "sm": "8px",
        "margin-desktop": "32px",
        "xs": "4px",
        "gutter": "16px",
        "base": "4px",
        "xl": "32px"
      },
      "fontFamily": {
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "title-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"]
      },
      "fontSize": {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
}
